### ISSUE TITLE
Breaks on indentation with odd number of spaces

### ISSUE THREAD

**Issue by heygarrett** [Darazaki/indent-o-matic#5]
https://github.com/Darazaki/indent-o-matic/blob/ee5283eedc75c32a7ad312b7ab54feee23582790/lua/indent-o-matic.lua#L88-L93

I work with Markdown files that use 3-space indentation. 🙈 Would it be feasible to check for either a range (eg, 2–8 spaces) or just more than two spaces rather than checking specifically for 2, 4 or 8 spaces?

**Comment by Darazaki** [comment]
Hi, sorry for the late answer. Sadly I can't really do that since allowing weird indentations could increase the number of cases where something that isn't an indentation gets treated as one:

```c
// Align arguments (6 spaces here)
int f(int x,
      int y);

int main(void) {
  // Actual indentation (2 spaces)
}
```

However, I could try to add user defined space configuration! Maybe:

```lua
require('indent-o-matic').setup {
    -- ...
    standard_widths = { 2, 3, 4, 8 }
}
```

Would that solves your issue?

**Comment by Darazaki** [comment]
Hi again @heygarrett! I've added the feature I've talked about since it seemed to be pretty close to what you wanted

If for some reason it doesn't work for you please let me know why and I'll reopen the issue to try and fix it

Have a nice day! :)
